//! `vela doc` — reference Markdown, generated from the schemas.
//!
//! `TOOLING.md §9`: the reference is generated from the single sources of truth already in the codebase —
//! widget prop schemas, the action registry, the diagnostic registry — so it *cannot* describe a prop that
//! does not exist, and the editor's completion list and the docs are the same list read twice. This is why
//! the prop schema is a data structure in `vela-ui` rather than prose in a manual: three consumers, one
//! definition.
//!
//! Every page is what `vela doc` prints, verbatim, which is what makes the drift check possible: the
//! reference under `docs/reference/` is compared against this command's output in a test, so a schema
//! change that nobody documented fails the suite rather than quietly making the manual wrong.
//!
//! # What it does not generate
//!
//! Effect signatures, because an `effect` is declared by the *project* — `effect rand.int(low, high) -> int`
//! is a line in a story, not a table in the engine — and a reference for one project's effects is not
//! documentation, it is that project's code. Public script APIs, because there are none yet: the engine's
//! surface a story can call is the builtins, and those are not a schema.

use std::io::Write;

use vela_diag::Severity;
use vela_ui::WidgetRegistry;
use vela_ui::actions::ActionRegistry;
use vela_ui::widgets::PropDecl;

use crate::command::{Command, Error};
use crate::commands::run::flag_value;

/// The `vela doc` command.
///
/// No base directory, unlike every other command: a reference for the engine is not a fact about a project,
/// and this one reads no files at all.
#[derive(Default)]
pub struct Doc;

impl Doc {
    /// Creates the command.
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Command for Doc {
    fn name(&self) -> &'static str {
        "doc"
    }

    fn about(&self) -> &'static str {
        "write the reference, generated from the schemas"
    }

    fn run(&self, args: &[String], out: &mut dyn Write) -> Result<(), Error> {
        let what = positional(args).unwrap_or("all");

        // `--out` is the one place in this tool that writes files, and it is deliberate: a reference page is
        // an artifact, and the point of generating it is that it lands in the repository where a reader
        // finds it. One line in a build script, and the drift check beside it keeps it honest.
        if let Some(dir) = flag_value(args, "--out") {
            return write(dir, what);
        }

        match what {
            "widgets" => {
                widgets(out);
                Ok(())
            }
            "actions" => {
                actions(out);
                Ok(())
            }
            "diagnostics" => {
                diagnostics(out);
                Ok(())
            }
            "all" => {
                for name in PAGES {
                    render(name, out);
                }
                Ok(())
            }
            other => Err(unknown(other)),
        }
    }
}

/// The pages, in the order `vela doc` prints them.
const PAGES: [&str; 3] = ["widgets", "actions", "diagnostics"];

/// One page, by name.
fn render(name: &str, out: &mut dyn Write) {
    match name {
        "actions" => actions(out),
        "diagnostics" => diagnostics(out),
        _ => widgets(out),
    }
}

/// What to say about a reference nobody has.
fn unknown(name: &str) -> Error {
    Error::usage(format!(
        "unknown reference `{name}`; expected widgets, actions, diagnostics, or nothing for all three"
    ))
}

/// Writes the pages into a directory, one file per page.
fn write(dir: &str, what: &str) -> Result<(), Error> {
    std::fs::create_dir_all(dir)
        .map_err(|error| Error::usage(format!("cannot create `{dir}`: {error}")))?;

    let names: Vec<&str> = if what == "all" {
        PAGES.to_vec()
    } else if PAGES.contains(&what) {
        vec![what]
    } else {
        return Err(unknown(what));
    };

    for name in names {
        let mut buffer: Vec<u8> = Vec::new();
        render(name, &mut buffer);

        let path = format!("{dir}/{name}.md");
        std::fs::write(&path, &buffer)
            .map_err(|error| Error::usage(format!("cannot write `{path}`: {error}")))?;
    }
    Ok(())
}

/// The widget reference: what common props every widget takes, then what each adds.
fn widgets(out: &mut dyn Write) {
    let registry = WidgetRegistry::builtin();
    let widgets: Vec<_> = registry.iter().collect();

    heading(
        out,
        "Widget reference",
        "Every widget a screen can write, and the props it takes.",
        "Generated by `vela doc widgets` from the prop schemas in `vela-ui` — the same definition the \
         checker and the completion list read (`SCREENS.md §9`), so a prop on this page is a prop the \
         compiler knows. Do not edit it by hand: a test fails when it is out of date.",
    );

    // The props every widget takes, once rather than in thirteen tables.
    let Some(first) = widgets.first() else {
        return;
    };
    let _ = writeln!(out, "## Props every widget takes\n");
    let _ = writeln!(
        out,
        "A `*` marks a prop a screen has to give. A prop that takes *a label or screen* is resolved by the \
         checker rather than read as a literal, so a typo is a diagnostic rather than a silent nothing.\n"
    );
    table(out, &first.common.iter().collect::<Vec<_>>());

    let _ = writeln!(out, "## Widgets\n");
    for widget in &widgets {
        let category = match widget.category {
            vela_ui::widgets::Category::Container => "a container",
            vela_ui::widgets::Category::Leaf => "draws, and holds nothing",
            vela_ui::widgets::Category::Interactive => "can be focused",
        };
        let shape = if widget.single_child {
            " Takes exactly one child."
        } else if widget.category.accepts_children() {
            " Takes children."
        } else {
            ""
        };

        let _ = writeln!(out, "### `{}`\n", widget.name);
        let _ = writeln!(out, "It is {category}.{shape}\n");

        let own: Vec<&PropDecl> = widget.own.iter().flat_map(|group| group.iter()).collect();
        if own.is_empty() {
            let _ = writeln!(out, "Adds no props of its own.\n");
            continue;
        }
        let _ = writeln!(out, "Adds:\n");
        table(out, &own);
    }
}

/// The action reference: what an `action` in a screen can call.
fn actions(out: &mut dyn Write) {
    let registry = ActionRegistry::builtin();
    let names = registry.names();

    heading(
        out,
        "Action reference",
        "Every action a screen can attach to a widget.",
        "Generated by `vela doc actions` from the action registry in `vela-ui`. Arguments are typed by the \
         same schema a widget's props use, so an action and a prop of the same name take the same kind of \
         value. Do not edit this page by hand: a test fails when it is out of date.",
    );

    for name in names {
        let Some(action) = registry.get(name) else {
            continue;
        };
        let args: Vec<String> = action
            .arg_names()
            .iter()
            .map(|arg| (*arg).to_string())
            .collect();
        let _ = writeln!(out, "## `{}({})`\n", action.name, args.join(", "));
        let _ = writeln!(out, "{}\n", sentence(action.doc));

        if action.args.is_empty() {
            continue;
        }
        let _ = writeln!(out, "| argument | takes | meaning |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for argument in action.args {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                argument.name,
                argument.ty.describe(),
                sentence(argument.doc)
            );
        }
        let _ = writeln!(out);
    }
}

/// The diagnostic reference: every code, in registry order.
fn diagnostics(out: &mut dyn Write) {
    let codes: Vec<_> = vela_diag::codes().collect();

    heading(
        out,
        "Diagnostic reference",
        "Every code `vela check` can report.",
        "Generated by `vela doc diagnostics` from `crates/vela-diag/codes.txt`, one code per line with its \
         severity — which is where a severity comes from, so a code cannot be an error here and a warning \
         there. Do not edit this page by hand: a test fails when it is out of date.",
    );

    let _ = writeln!(
        out,
        "{} codes: {} error(s), {} warning(s), {} lint(s).\n",
        codes.len(),
        count_severity(&codes, Severity::Error),
        count_severity(&codes, Severity::Warning),
        count_severity(&codes, Severity::Lint)
    );

    let _ = writeln!(out, "| code | severity | meaning |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for code in codes {
        let _ = writeln!(
            out,
            "| `{code}` | {} | {} |",
            code.severity().as_str(),
            sentence(code.title())
        );
    }
}

/// How many codes have a severity.
fn count_severity(codes: &[vela_diag::Code], severity: Severity) -> usize {
    codes
        .iter()
        .filter(|code| code.severity() == severity)
        .count()
}

/// The title, introduction, and provenance a page starts with.
fn heading(out: &mut dyn Write, title: &str, summary: &str, provenance: &str) {
    let _ = writeln!(out, "# {title}\n");
    let _ = writeln!(out, "{summary}\n");
    let _ = writeln!(out, "{provenance}\n");
}

/// A prop table.
fn table(out: &mut dyn Write, props: &[&PropDecl]) {
    let _ = writeln!(out, "| prop | takes | | meaning |");
    let _ = writeln!(out, "| --- | --- | --- | --- |");
    for prop in props {
        let mark = if prop.required { "*" } else { "" };
        let _ = writeln!(
            out,
            "| `{}` | {} | {mark} | {} |",
            prop.name,
            prop.ty.describe(),
            sentence(prop.doc)
        );
    }
    let _ = writeln!(out);
}

/// A doc string as a sentence, so a table cell reads as prose.
///
/// The schema's `doc` fields are written as fragments — "space inside the edges" — because that is what a
/// completion list shows beside a name. In a table they want a capital and a full stop, and computing that
/// here keeps the schema free of presentation.
fn sentence(doc: &str) -> String {
    let mut chars = doc.trim().chars();
    let Some(first) = chars.next() else {
        return String::new();
    };

    let mut sentence = first.to_uppercase().collect::<String>();
    sentence.push_str(chars.as_str());
    if !sentence.ends_with(['.', '!', '?']) {
        sentence.push('.');
    }
    sentence.replace('|', "\\|")
}

/// The first positional argument, skipping flags and the values they take.
fn positional(args: &[String]) -> Option<&str> {
    let mut index = 0;
    while index < args.len() {
        let arg = args[index].as_str();
        // `--out` takes a value, and the value is not the reference being asked for: skipping it here is
        // what makes `vela doc --out docs/reference` mean "everything, written there".
        if arg == "--out" {
            index += 2;
            continue;
        }
        if arg.starts_with('-') {
            index += 1;
            continue;
        }
        return Some(arg);
    }
    None
}
