[package]
name = "vela-migrate"
description = "The Ren'Py `.rpy` to `.vela` transpiler and its compat report."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.vela]
rank = 8

[dependencies]
vela-span.workspace = true
vela-syntax.workspace = true
vela-compile.workspace = true
vela-diag.workspace = true

[lints]
workspace = true
