[package]
name = "vela-text"
description = "Text shaping, line breaking, layout, and the glyph atlas."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.vela]
rank = 1

[dependencies]
swash = "0.2.10"
unicode-linebreak = "0.1.5"
vela-span.workspace = true

[lints]
workspace = true

[dev-dependencies]
swash = "0.2.10"
unicode-linebreak = "0.1.5"
